# -*- coding: utf-8 -*-
"""chinny

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13LWJee5YZK0iK7QYS_g00O-RHGcv10b0
"""

x = 5
print(x>0 and x<10)

n = 25
print(n%2 == 0 or n%4 == 0)

print('p' in 'apple')
print('c' in 'cidar')
print('z' in 'kosi')
print('' in 'kosi')

print('k' not in 'kosi')
print('k' not in 'stanley')

print('a' in ["apple", "banana", 'application', 'a'])

assert type(9//5) == int
#assert type(9.0//5) == int
print(9//5)

lst = ['a', 'b', 'c']

first_type = type(lst[0])
for item in lst:
  assert type(item) == first_type

lst2 = ['a', 'b', 'c', 17]
first_type = type(lst2[0])
for item in lst2:
  assert type(item) == first_type

lst = ['a', 'b', 'c']
assert len(lst) < 10

x = 154

if x % 2 == 0:
  print(x, "is even")
  print("IT IS EVEN")
else:
  print(x, "is odd")
  print("IT IS ODD")

x = -10
if x < 0:
  print("The negative number ", x, "is not valid here")
print("Hey")

x = 100
y = 100

if x < y:
  print("x is less than y")
elif x > y:
  print("x is greater than y")
else:
  print("x and y must be equal")

x = 5
y = 4

if x < y:
  z = x

else:
  if y > x:
    x = y

  else:
    #x must be equal to y
    z = 0
print(z)

phrase = "What a wonderful day to program"
tot = 0

for char in phrase:
  if char != " ":
    tot += 1

print(tot)

s = "What if we went to the zooo"
x = 0

for ch in s:
  if ch in ("a", "e", "i", "o", "u"):
    x += 1
print(x)

num = [9,3, 8, 11, 5, 29, 2]
lar = num[0]

for n in num:
  if n > lar:
    lar = n

print(lar)

fruit = ["banana", "apple", "cheery"]
print(fruit)

fruit[0] = "peer"
fruit[-1] = "orange"
print(fruit)

alist = ['a', 'b', 'c', 'd', 'e', 'f']
alist[1:3] = ['x', 'y', 'z']
print(alist)

alist = ['a', 'b', 'c', 'd', 'e', 'f']
alist[1:3] = []
print(alist)

greeting = "hello world"
greeting[0] = "J"
print(greeting)

greeting = "hello world"
newgreet = "G" + greeting[1:]
print(newgreet)

phrase = "many moons"
exp_phrase = phrase + "and many stars"
large_phrase = exp_phrase + "little"

a = ["one", "two", "three"]
del a[1]
print(a)

alist = ['a', 'b', 'c', 'd']
del alist[1:5]
print(alist)

a = "banana"
b = "banana"

print(a is b)